name: tfgpumodern
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - aom=3.9.1
  - astunparse=1.6.3
  - attrs=23.2.0
  - blinker=1.8.2
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.14.3
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - certifi=2024.6.2
  - cffi=1.16.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cryptography=42.0.8
  - cuda-crt-tools=12.5.40
  - cuda-cudart=12.5.39
  - cuda-cudart_linux-64=12.5.39
  - cuda-nvcc-tools=12.5.40
  - cuda-nvrtc=12.5.40
  - cuda-nvtx=12.5.39
  - cuda-nvvm-tools=12.5.40
  - cuda-version=12.5
  - cudnn=8.9.7.29
  - dav1d=1.2.1
  - flatbuffers=23.5.26
  - freetype=2.12.1
  - frozenlist=1.4.1
  - gast=0.5.5
  - giflib=5.2.2
  - google-auth=2.31.0
  - google-auth-oauthlib=1.2.0
  - google-pasta=0.2.0
  - grpcio=1.59.3
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - imagecodecs=2024.1.1
  - imageio=2.34.2
  - importlib-metadata=8.0.0
  - jxrlib=1.1
  - keras=2.15.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libavif16=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=12.5.2.13
  - libcufft=11.2.3.18
  - libcurand=10.3.6.39
  - libcurl=8.8.0
  - libcusolver=11.6.2.40
  - libcusparse=12.4.1.24
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgrpc=1.59.3
  - libhwy=1.1.0
  - libjpeg-turbo=3.0.0
  - libjxl=0.10.2
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libnvjitlink=12.5.40
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libprotobuf=4.24.4
  - libre2-11=2023.09.01
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=2.1.5
  - ml_dtypes=0.2.0
  - multidict=6.0.5
  - nccl=2.22.3.1
  - ncurses=6.5
  - networkx=3.3
  - numpy=1.26.4
  - oauthlib=3.2.2
  - openjpeg=2.5.2
  - openssl=3.3.1
  - opt_einsum=3.3.0
  - packaging=24.1
  - pillow=10.4.0
  - pip=24.0
  - protobuf=4.24.4
  - pthread-stubs=0.4
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.22
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-flatbuffers=24.3.25
  - python_abi=3.11
  - pyu2f=0.1.5
  - pywavelets=1.6.0
  - rav1e=0.6.6
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rsa=4.9
  - scikit-image=0.24.0
  - scipy=1.14.0
  - setuptools=70.1.1
  - six=1.16.0
  - snappy=1.1.10
  - svt-av1=2.1.2
  - tensorboard=2.15.2
  - tensorboard-data-server=0.7.0
  - tensorflow=2.15.0
  - tensorflow-base=2.15.0
  - tensorflow-estimator=2.15.0
  - tensorflow-gpu=2.15.0
  - termcolor=2.4.0
  - tifffile=2024.7.2
  - tk=8.6.13
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.2
  - werkzeug=3.0.3
  - wheel=0.43.0
  - wrapt=1.14.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yarl=1.9.4
  - zfp=1.0.1
  - zipp=3.19.2
  - zlib-ng=2.0.7
  - zstandard=0.22.0
  - zstd=1.5.6
